"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" load plugins from vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let vundle manage vundle
Plugin 'VundleVim/Vundle.vim'

" utilities
Plugin 'kien/ctrlp.vim' " fuzzy find files
Plugin 'scrooloose/nerdtree' " file drawer, open with :NERDTreeToggle
Plugin 'scrooloose/syntastic' " Verification des erreurs
Plugin 'bling/vim-airline'
Plugin 'ervandew/supertab'
Plugin 'Valloric/YouCompleteMe'
Plugin 'majutsushi/tagbar'
Plugin 'tpope/vim-fugitive'
call vundle#end()
filetype plugin indent on

set autoread " detect when a file is changed
set rnu
set number 
set clipboard=unnamed

" make backspace behave in a sane manner
set backspace=indent,eol,start

" Tab control
set expandtab " tabs ftw
set smarttab " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
set tabstop=2 " the visible width of tabs
set softtabstop=2 " edit as if the tabs are 4 characters wide
set shiftwidth=2 " number of spaces to use for indent and unindent
set shiftround " round indent to a multiple of 'shiftwidth'

set encoding=utf8
syntax on
let g:solarized_termcolors=256
set t_Co=16 
set background=dark
colorscheme molokai 

let g:molokai_original = 1
let g:rehash256 = 1

set autoindent " automatically set indent of new line
set smartindent
set textwidth=80
set hidden
set showcmd

set laststatus=2 " show the satus line all the time

"Delete time for switch mode
set timeoutlen=1000 ttimeoutlen=0
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" close NERDTree after a file is opened
let g:NERDTreeQuitOnOpen=1
" show hidden files in NERDTree
let NERDTreeShowHidden=1
" NERDTRee
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <C-m> :NERDTreeToggle<CR>

"Control P
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

"TagBar
nmap <C-t> :TagbarToggle<CR>

"Vim-airline
let g:airline#extensions#tabline#enabled = 1

"Stop using arow 
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Previous buffer
:nnoremap <C-j> :bp<CR>
" Next buffer
:nnoremap <C-n> :bn<CR>
" Kill buffer
map <C-d> :bd<CR>

:set cursorline
:set cursorcolumn

"Language
:set spelllang=en,fr
map <silent> <F7> "<Esc>:silent setlocal spell! spelllang=en<CR>"
map <silent> <F6> "<Esc>:silent setlocal spell! spelllang=fr<CR>"
" Delete Delay
set timeoutlen=1000 ttimeoutlen=0
