export ZSH=/$HOME/.oh-my-zsh
# Theme
ZSH_THEME="bureau"

#Plugin
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/dsa_id"

#Alias
alias g = "git"
# Automatically launch a tmux session
if [[ -z "$TMUX" ]]
then
  ID="`tmux ls | grep -vm1 attached | cut -d: -f1`"
  if [[ -z "$ID" ]]
  then
    tmux new-session
  else
    tmux attach-session -t "$ID"
  fi
fi

#Delete delay
KEYTIMEOUT=1
